private function convert_hindi_text($text) {
    $hindi_fixes = array(
        // Basic Words
        'laca/' => 'संबंध',
        'iQyu' => 'फलन',
        'izkar' => 'प्रांत',
        'lgizkar' => 'सहप्रांत',
        'ifjlj' => 'परिसर',
        'vo/kj.kkvksa' => 'संकल्पनाओं',
        'Lej.k' => 'याद',
        'd{kk' => 'कक्षा',
        'okLrfod' => 'वास्तविक',
        'ekuh;' => 'मानीय',
        'vkys[kksa' => 'आलेखों',
        'lfgr' => 'सहित',
        'ifjp;' => 'परिचय',
        'xf.kr' => 'गणित',
        "'kCn" => 'शब्द',
        "loaQYiuk" => 'संकल्पना',
        "vaxzs”kh" => 'अंग्रेजी',
        "Hkkekk" => 'भाषा',
        "vekZ" => 'अर्थ',
        "vuqlkj" => 'अनुसार',
        "oLrq,¡" => 'वस्तुएँ',
        "ijLij" => 'परस्पर',
        "lacaf/r" => 'संबंधित',
        "vfHkKs;" => 'पहचान योग्य',
        "dM+h" => 'कड़ी',
        "LowQy" => 'विद्यालय',
        "fo|kfekZ;ksa" => 'विद्यार्थियों',
        "leqPp;" => 'समुच्चय',
        "mnkgj.k" => 'उदाहरण',
        
        // Small Words & Grammar
        ',oa' => 'और',
        'rekk' => 'तथा',
        'vkfn' => 'आदि',
        'dk' => 'का',
        'dh' => 'की',
        'osQ' => 'के',
        'ls' => 'से',
        'ij' => 'पर',
        'rks' => 'तो',
        'vkSj' => 'और',
        ';fn' => 'यदि',
        'fd' => 'कि',
        'bl' => 'इस',
        'ml' => 'उस',
        'osQ' => 'के',
        'dks' => 'को',
        'esa' => 'में',
        'gS' => 'है',
        'gSa' => 'हैं',
        'gksrh' => 'होती',
        'gksrs' => 'होते',
        'gks' => 'हो',
        'tk' => 'जा',
        'pqdk' => 'चुका',
        'pqosQ' => 'चुके',
        'djk;k' => 'दिया',
        'ns[kk' => 'देखा',
        'Kkr' => 'ज्ञात',
        'fl¼' => 'सिद्ध',
        'tk¡p' => 'जाँच',
        'crykb,' => 'बताइए',
        'dhft,' => 'कीजिए',
        
        // Partial Word Endings
        'ksa' => 'ों',
        'k' => '्',
        's' => '्',
        'a' => 'ा',
        'aa' => 'ा',
        'i' => 'ि',
        'I' => 'ी',
        'ee' => 'ी',
        'u' => 'ु',
        'oo' => 'ू',
        'e' => 'े',
        'ai' => 'ै',
        'o' => 'ो',
        'au' => 'ौ',
        
        // Common Prefixes/Suffixes
        'fofHkUu' => 'विभिन्न',
        'izdkj' => 'प्रकार',
        'muosQ' => 'उनके',
        'fdlh' => 'किसी',
        'leqPp;' => 'समुच्चय',
        'nks' => 'दो',
        'rhu' => 'तीन',
        'pkj' => 'चार',
        'vU;' => 'अन्य',
        'lkekU;' => 'सामान्य',
        'egRoiw.kZ' => 'महत्वपूर्ण',
        'vf/d' => 'अधिक',
        'de' => 'कम',
        'cM+k' => 'बड़ा',
        'NksVk' => 'छोटा',
        
        // Special Characters
        '¿' => '?',
        '¡' => '!',
        '––' => '—',
        
        // Your Document Specific
        'fLekr' => 'स्थित',
        'lerY;' => 'तल',
        'js[kkvksa' => 'रेखाओं',
        'yac' => 'लंब',
        'lekUrj' => 'समांतर',
        'f=kHkqt' => 'त्रिभुज',
        'lokZxale' => 'सर्वांगसम',
        'levi' => 'समरूप',
        'cgqHkqt' => 'बहुभुज',
        'Lekku' => 'स्थान',
        'eksgYys' => 'मोहल्ले',
        'iRuh' => 'पत्नी',
        'firk' => 'पिता',
        'HkkbZ' => 'भाई',
        'cgu' => 'बहन',
        'vk;q' => 'आयु',
        'vf/d' => 'अधिक',
        'Å¡pkbZ' => 'ऊँचाई',
        'txg' => 'जगह',
        'jgrk' => 'रहता',
    );
    
    foreach ($hindi_fixes as $garbled => $proper) {
        $text = str_replace($garbled, $proper, $text);
    }
    
    return nl2br(htmlspecialchars($text, ENT_QUOTES, 'UTF-8'));
}
